name: ItemSerializationPlugin
version: 1.0
main: com.example.ItemSerializationPlugin
api-version: 1.20.1

depend:
  paper-api: "latest"

commands:
  serialize:
    description: Serializes an item
    usage: /serialize <item>
    permission: itemserialize.serialize
